version: "3"
services:
  devops-db:
    image: "postgres:latest"
    container_name: "students_app"
    environment:
      - POSTGRES_USER=kiii
      - POSTGRES_PASSWORD=kiii123
      - POSTGRES_DB=students
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  devops:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - devops-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://devops-db:5432/students
      - SPRING_DATASOURCE_USERNAME=kiii
      - SPRING_DATASOURCE_PASSWORD=kiii123
    ports:
      - "9090:9090"

volumes:
  postgres-data:
